---
- name: playbook to pre-setup ocp
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    namespace_prefix: testing
  tasks:

  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: "{{ item }}"
      kind: Namespace
      state: "{{ namespace_state }}"
    loop:
    - "{{ namespace_prefix }}-dev1"
    - "{{ namespace_prefix }}-dev2"
    - "{{ namespace_prefix }}-qa1"
    - "{{ namespace_prefix }}-qa2"
