- name: "Install database vms into all namespaces"
  hosts: all
  vars:
    namespace_prefix: testing
    namespace: 
      - "{{ namespace_prefix }}-dev1"
      - "{{ namespace_prefix }}-dev2"
      - "{{ namespace_prefix }}-qa1"
      - "{{ namespace_prefix }}-qa2"
  vars_files:
    - vars.yml

  tasks:
    - name: "Create Namespaces"
      kubernetes.core.k8s:
        state: present
        template: namespace.yml.j2
      loop: "{{ namespace }}"

    - name: "Create VirtualMachine"
      kubernetes.core.k8s:
        state: present
        template: virtualmachine.yml.j2
        namespace: "{{ item }}"
      loop: "{{ namespace }}"
