---
- name: Playbook to start a openshift virt VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: start a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
      state: present
      running: true
