---
- name: Playbook to start a openshift virt VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: start a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
      state: present
      running: false
    register: ocp_vm_status
    changed_when: ocp_vm_status.result.status.printableStatus == 'Running'
