---
- name: Playbook to stop an openshift virt VM
  hosts: all
  tasks:
  - name: stop a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
      state: present
      running: false
    register: ocp_vm_status
    changed_when: ocp_vm_status.result.status.printableStatus == 'Stopped'
