---
- name: Playbook to stop an openshift virt VM
  hosts: all
  tasks:
  - name: stop a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: phils-test
      namespace: default
      state: present
      running: false
    register: ocp_vm_status
    changed_when: ocp_vm_status.result.status.printableStatus == 'Running'
