- name: Authenticate with token and return all VirtualMachineInstances for all accessible namespaces
  plugin: kubevirt.core.kubevirt
  connections:
    - host: https://api.ocp.example.com:6443
      username: admin
      password: rBCvN2MoiO,9
      validate_certs: false
